### ISSUE TITLE
Errore chiamata "invoice/status" - URGENZA BASSA

### ISSUE THREAD

**Issue by AndreaCashItaly** [jambtc/cash-register-docs#2]
Quando si passa un parametro errato alla chiamata "invoice/status" è possibile implementare una risposta sempre in json con i parameteri "error" e "message" (come accade per la chiamata "invoice/pay")?
Al momento, se viene passato un id errato o non viene passato affatto, va in eccezione e la risposta che ottengo dall'oggetto WebClient in C# è "Errore del server 400".
![screencapture-207-180-212-166-2019-09-13-11_48_53](https://user-images.githubusercontent.com/55200226/64853805-8167c280-d61c-11e9-8e08-7d45c2f3b0bb.png)

**Comment by jambtc** [comment]
Si. in effetti va in eccezione. Faccio in modo che risponde in json con il tipo di errore.

**Comment by jambtc** [comment]
Ho trasformato le risposte da throw new exception in json. Nel prossimo update le trovi operative.
